package model.exceptions;

public class DomainException extends Exception{ //ADICIONA-SE 'RUNTIME' COLADO AO 'EXCEPTION' PARA NÃO SE TER A NECESSIDADE DE TRATAMENTO DAS EXCECOES. PODENDO APAGAR AS 'THROWS DECLARATIONS', NO ENTANTO, O PROGRAMA IRA QUEBRAR DANDO A MENSAGEM DE ERRO PADRAO DO JAVA.
	private static final long serialVersionUID = 1L; // O EXCEPTION É UM TIPO 'SERIALIZABLE" E PRECISA ENTÃO DE UM NUMERO DE VERSÃO, QUE É DEFINIDA DESSA FORMA
	
	public DomainException(String msg) { // ADICIONAR UM CONSTRUTOR QUE RECEBE UM STRING COMO ARGUMENTO
		super(msg); // PERMITE QUE EU POSSA INSTANCIAR MINHA EXCECAO PERSONALIZADA, PASSANDO UMA MENSAGEM PARA ELA. E A MENSAGEM FICA ARMAZENADA DENTRO DA EXCECAO
	}

}
